clear all;
close all;
clc;
t=0:0.001:1;
am=input('Amplitude of the Modulated Signal');
fm=input('Frequency of the Modulated signal');
ac=input('Amplitude of the carrier signal');
fc=input('Frequency of the carrier signal');
mf=input('Modulation Index');
xt=am*cos(2*pi*fm*t);
subplot(4,1,1);
plot(t,xt,'y');
title('Message signal');
xlabel('TIME');
ylabel('AMPLITUDE');
ct=ac*cos(2*pi*fc*t);
subplot(4,1,2);
plot(t,ct,'m');
title('Carrier signal');
xlabel('TIME');
ylabel('AMPLITUDE');
sfmt=ac*cos((2*pi*fc*t)+(mf*sin(2*pi*fm*t)));
subplot(4,1,3);
plot(t,sfmt,'g');
title('Frequency Modulated');
xlabel('TIME');
ylabel('AMPLITUDE');
