clear all;
close all;
clc;
t=0:0.001:1;
am=input('Amplitude of the Modulated Signal');
fm=input('Frequency of the Modulated signal');
ac=input('Amplitude of the carrier signal');
fc=input('Frequency of the carrier signal');
mp=input('Sensitivity');
xt=am*cos(2*pi*fm*t);
subplot(3,1,1);
plot(t,xt,'b');
title('Message signal');
xlabel('TIME');
ylabel('AMPLITUDE');
ct=ac*cos(2*pi*fc*t);
subplot(3,1,2);
plot(t,ct,'m');
title('Carrier signal');
xlabel('TIME');
ylabel('AMPLITUDE');
sfmt=ac*cos((2*pi*fc*t)+(mp*cos(2*pi*fm*t)));
subplot(3,1,3);
plot(t,sfmt,'g');
title('Phase Modulated');
xlabel('TIME');
ylabel('AMPLITUDE');
