clear all;
close all;
clc;
t=0:0.001:1;
am=input('Amplitude of the Modulated Signal');
fm=input('Frequency of the Modulated signal');
ac=input('Amplitude of the carrier signal');
fc=input('Frequency of the carrier signal');
xt=am*cos(2*pi*fm*t);
subplot(5,1,1);
plot(t,xt);
title('Message signal');
xlabel('TIME');
ylabel('AMPLITUDE');
xh=am*sin(2*pi*fm*t);
subplot(5,1,2);
plot(t,xh);
title('Hilbert transform Message signal');
xlabel('TIME');
ylabel('AMPLITUDE');
ct=ac*cos(2*pi*fc*t);
subplot(5,1,3);
plot(t,ct);
title('Carrier signal');
xlabel('TIME');
ylabel('AMPLITUDE');
st1=(xt.*cos(2*pi*fc*t))-(xh.*sin(2*pi*fc*t));
subplot(5,1,4);
plot(t,st1);
title('Upper side band');
xlabel('TIME');
ylabel('AMPLITUDE');
st2=(xt.*cos(2*pi*fc*t))+(xh.*sin(2*pi*fc*t));
subplot(5,1,5);
plot(t,st2);
title('Lower side band');
xlabel('TIME');
ylabel('AMPLITUDE');
